### ISSUE TITLE
deploy contracts to mainnet via truffle

### ISSUE THREAD

**Issue by EverythingIsNothing** [CyberMiles/travis#34]
deploy failed "invalid chain id for signer"
```
Qiu:MetaCoin miniQ$ truffle migrate --network live

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Starting migrations...
======================
> Network name:    'live'
> Network id:      18
> Block gas limit: 8192000000


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
Error:  *** Deployment Failed ***

"Migrations" -- code:1 log:"invalid chain id for signer" fee:<> .

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.8 (core: 5.0.8)
Node v10.15.0
```

contract code
```
pragma solidity >=0.4.25 <0.6.0;

// This is just a simple example of a coin-like contract.
// It is not standards compatible and cannot be expected to talk to other
// coin/token contracts. If you want to create a standards-compliant
// token, see: https://github.com/ConsenSys/Tokens. Cheers!

contract MetaCoin {
	mapping (address => uint) balances;

	event Transfer(address indexed _from, address indexed _to, uint256 _value);

	constructor() public {
		balances[tx.origin] = 1000;
	}

	function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		emit Transfer(msg.sender, receiver, amount);
		return true;
	}

	function getBalance(address addr) public view returns(uint) {
		return balances[addr];
	}
}
```
truffle config
```
live: {
        provider: function() {
            return new HDWalletProvider(privateKeys,"https://rpc.cybermiles.io:8545");
        },
     // host: "https://rpc.cybermiles.io", // Random IP for example purposes (do not use)
     // port: 8545,
     network_id: "*"
    },
```

**Comment by hdulqs** [comment]
![image](https://user-images.githubusercontent.com/5356389/56208991-0f974700-6085-11e9-9b7a-e7a334f273d1.png)

 不知道是不是这里的代码逻辑需要调整？
tx.ChainId() <= 0 ?

**Comment by EverythingIsNothing** [comment]
i debug HDWalletProvider (truffle-hdwallet-provider-privkey)index.js code , find  function signTransaction   console.log(tx._chainId) //output: 0, but i config 18 in truffle-config.js
```
signTransaction: function (txParams, cb) {
          console.log('signTransaction txParams:', txParams)
        let pkey
        if (tmpWallets[txParams.from]) {
          pkey = tmpWallets[txParams.from].getPrivateKey()
        } else {
          cb('Account not found')
        }
        var tx = new Transaction(txParams)
        tx.sign(pkey)
        var rawTx = '0x' + tx.serialize().toString('hex')
        console.log('signTransaction rawTx:', rawTx)
        console.log('signTransaction tx:', tx)
        cb(null, rawTx)
      }
```
[HDWalletProvider code link](https://github.com/rhlsthrm/truffle-hdwallet-provider-privkey/blob/master/index.js)
i change signTransaction code:
```
signTransaction: function (txParams, cb) {
          console.log('signTransaction txParams:', txParams)
        let pkey
        if (tmpWallets[txParams.from]) {
          pkey = tmpWallets[txParams.from].getPrivateKey()
        } else {
          cb('Account not found')
        }
        var tx = new Transaction(txParams)
        tx._chainId = 18
        tx.sign(pkey)
        var rawTx = '0x' + tx.serialize().toString('hex')
        console.log('signTransaction rawTx:', rawTx)
        console.log('signTransaction tx:', tx)
        cb(null, rawTx)
      }
```
it works ！i have successd to deploy contracts to CyberMiles via truffle and web3-1.0!
